// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz-tPnU1nz1VvY7G1JgiQPHTpGh5AJQqI',
    appId: '1:609035717673:web:8fb9b2765004ad9d75e038',
    messagingSenderId: '609035717673',
    projectId: 'agriupd2',
    authDomain: 'agriupd2.firebaseapp.com',
    storageBucket: 'agriupd2.firebasestorage.app',
    measurementId: 'G-0MR7JQLVHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkb3qE5WFvbzobRlqpD0JKJ_TAzQigIKI',
    appId: '1:609035717673:android:f80081bcead5f77375e038',
    messagingSenderId: '609035717673',
    projectId: 'agriupd2',
    storageBucket: 'agriupd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByePP9YAN35rqNRb3XkUPgW_qD8ANsDgw',
    appId: '1:609035717673:ios:a7e51dc8e060e2fb75e038',
    messagingSenderId: '609035717673',
    projectId: 'agriupd2',
    storageBucket: 'agriupd2.firebasestorage.app',
    iosBundleId: 'com.example.agriUpd2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByePP9YAN35rqNRb3XkUPgW_qD8ANsDgw',
    appId: '1:609035717673:ios:a7e51dc8e060e2fb75e038',
    messagingSenderId: '609035717673',
    projectId: 'agriupd2',
    storageBucket: 'agriupd2.firebasestorage.app',
    iosBundleId: 'com.example.agriUpd2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz-tPnU1nz1VvY7G1JgiQPHTpGh5AJQqI',
    appId: '1:609035717673:web:4a0db50fada8840f75e038',
    messagingSenderId: '609035717673',
    projectId: 'agriupd2',
    authDomain: 'agriupd2.firebaseapp.com',
    storageBucket: 'agriupd2.firebasestorage.app',
    measurementId: 'G-9L81TSK539',
  );
}
